### PR TITLE
Feature2 updated

### PR DESCRIPTION
**Pull request by johnmcg04**
2. "As a member of the HR team I want to be able to create a new delivery employee. I should be able to store a name, salary, bank account number and national insurance number"

Created the Employee table.

Created the Employee_financials table.

Inserted values of the new delivery employee the HR member would like to add for the Employee table.

Inserted values for the delivery employee into the Employee_financials table the HR member would like to add.

Split the employee table into the Employee_financials table to split up the data of an Employee and the financials for the employee.

### CODE REVIEW

**Review by CharlesM988 — APPROVED** [review]
Looks great!

**Review by lullabelle — CHANGES_REQUESTED** [review]
hi im a bit confused sorry!
Is this new table for the delivery employee in Requirement 2? Am i expecting fields for  name, salary, bank account number and national insurance number?

**Review by johnmcg04 — COMMENTED** [review]
2. "As a member of the HR team I want to be able to create a new delivery employee. I should be able to store a name, salary, bank account number and national insurance number"

Created the Employee table.

Created the Employee_financials table.

Inserted values of the new delivery employee the HR member would like to add for the Employee table.

Inserted values for the delivery employee into the Employee_financials table the HR member would like to add.

Split the employee table into the Employee_financials table to split up the data of an Employee and the financials for the employee.

**Review by lullabelle — APPROVED** [review]
good to go

**Pull request merged**
