### PR TITLE
Feature5

### PR DESCRIPTION
**Pull request by Breanna-loughrey**
5  "As a member of the Management team I want to be able to assign delivery employees to a project. A delivery employee can work on multiple projects at the same time and can also work on the same project more than once"

Created Table  Employee_Projects to link Employee and Projects through composite key employeeID ProjectID.

### CODE REVIEW

**Review by johnmcg04 — COMMENTED** [review]
it will do I guess

**Review by UserConor — APPROVED** [review]
Not bad

**Review by lullabelle — CHANGES_REQUESTED** [review]
Is this pull request for 2 features? ie no5 and no 6? If so they will need to be separated into 2 pull requests or if your commit description is wrong update that

**Comment by Breanna-loughrey** [comment]
> Is this pull request for 2 features? ie no5 and no 6? If so they will need to be separated into 2 pull requests or if your commit description is wrong update that

I have edited it so it is only a pull request for no5, thanks

**Review by johnmcg04 — COMMENTED** [review]
all good

**Review by johnmcg04 — APPROVED** [review]

**Review by lullabelle — CHANGES_REQUESTED** [review]
Just one more thing give your code files more succinct naming conventions for eg maybe call this file ASSIGNDeliverEmployeesToProject.sql like put the action at the start of the statement.
CREATE, INSERT, UPDATE

**Review by lullabelle — APPROVED** [review]
looks good to go!

**Pull request merged**
